package com.soccialy.backend.controller;

import com.soccialy.backend.dto.AuthRequest;
import com.soccialy.backend.dto.AuthResponse;
import com.soccialy.backend.dto.GoogleAuthRequest;
import com.soccialy.backend.service.AuthService;
import com.soccialy.backend.exception.AuthFailedException;
import jakarta.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

/**
 * REST Controller for authentication endpoints within the Soccialy platform.
 * <p>
 * This controller serves as the primary entry point for security-related operations. It manages
 * the communication between the client-side authentication forms and the internal business
 * logic. Specifically, it handles user registration, traditional credential-based login,
 * and OAuth2 integration via Google.
 * </p>
 * <p>
 * To maintain a clean separation of concerns, this controller does not contain manual error
 * handling blocks; instead, all authentication-related exceptions and data validation errors
 * are intercepted and formatted by a global Exception Handler.
 * </p>
 *
 * @author Apetrei Ionuț-Teodor
 */
@RestController
@RequestMapping("/api/v1/auth")
public class AuthController
{
    private final AuthService authService;

    @Autowired
    public AuthController(AuthService authService)
    {
        this.authService = authService;
    }

    /**
     * Endpoint for local user registration.
     * <p>
     * This method receives user details, including a unique username and email. It enforces
     * structural validation on the input data before delegating the creation logic to the
     * service layer. On success, it returns a 201 Created status along with a signed JWT
     * to allow the user to bypass a separate login step immediately after signing up.
     * </p>
     *
     * @param request An {@link AuthRequest} object containing the necessary registration
     * data (username, email, raw password, and fullname).
     * @return A {@link ResponseEntity} wrapping the {@link AuthResponse}, which contains
     * the generated JWT and the newly created user's profile metadata.
     * @throws AuthFailedException if the registration fails due to duplicate credentials or
     * business logic violations.
     */
    @PostMapping("/register")
    public ResponseEntity<AuthResponse> register(@Valid @RequestBody AuthRequest request)
    {
        AuthResponse response = authService.registerUser(request);
        return ResponseEntity.status(HttpStatus.CREATED).body(response);
    }

    /**
     * Endpoint for local user login using email and password.
     * <p>
     * Validates the user's provided email format and structural requirements before checking
     * the email against the database and the raw password against the stored BCrypt hash.
     * If the credentials match, a session-initiating JWT is returned to the client.
     * </p>
     *
     * @param request An {@link AuthRequest} object containing the login credentials
     * (specifically the email and password fields).
     * @return A {@link ResponseEntity} wrapping the {@link AuthResponse} containing the
     * authenticated user's information and the access token.
     * @throws AuthFailedException if the email is not found, the password is incorrect,
     * or if the account is restricted to OAuth2 login only.
     */
    @PostMapping("/login")
    public ResponseEntity<AuthResponse> login(@Valid @RequestBody AuthRequest request)
    {
        AuthResponse response = authService.loginUser(request);
        return ResponseEntity.ok(response);
    }

    /**
     * Endpoint for Google OAuth2 login.
     * <p>
     * This method consumes a Google ID Token generated by the frontend. It triggers
     * an exchange process where the token is verified for authenticity and then
     * converted into an internal system JWT. This facilitates a "One-Tap" or
     * "Sign in with Google" user experience.
     * </p>
     *
     * @param request A {@link GoogleAuthRequest} containing the raw Google ID Token
     * string obtained from the Google Identity Services API.
     * @return A {@link ResponseEntity} wrapping the {@link AuthResponse}, including
     * user details retrieved from the Google payload and the internal JWT.
     * @throws AuthFailedException if the token is null, empty, expired, or fails
     * cryptographic verification with Google's servers.
     */
    @PostMapping("/google")
    public ResponseEntity<AuthResponse> googleLogin(@RequestBody GoogleAuthRequest request)
    {
        if (request.getToken() == null || request.getToken().isBlank())
        {
            throw new AuthFailedException("Google token is required.");
        }

        AuthResponse response = authService.loginUserGoogle(request.getToken());
        return ResponseEntity.ok(response);
    }
}