spring.application.name=backend

spring.config.import=optional:file:.env

server.port=9090

app.ai.base-url=${AI_API_URL:http://localhost:5000}


# ==================================================================================================== #

#                                   JWT AUTHENTICATION CONFIGURATION                                   #

# ==================================================================================================== #

# AUTHOR: Apetrei Ionut-Teodor



app.jwt.secret=${JWT_SECRET_KEY:4f6a72614a5170337336763979244226452948404d635166546a576e5a713474}

app.jwt.expiration-ms=86400000



# ==================================================================================================== #

#                                             GOOGLE OAUTH2                                            #

# ==================================================================================================== #

# AUTHOR: Apetrei Ionut-Teodor

app.google.client-id=${GOOGLE_CLIENT_ID:911324852425-825vonv605l4777qimkcu03uann3ufoa.apps.googleusercontent.com}



# ==================================================================================================== #

#                                         DATABASE CONFIGURATION                                       #

# ==================================================================================================== #

spring.datasource.url=jdbc:mysql://socially-database.ch80ks4wcw1v.eu-west-1.rds.amazonaws.com:3306/socially

spring.datasource.username=socially_user

spring.datasource.password=<iOWf,jR14)({S#k9Mq=A|!MaxxFGe

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect