name: "SonarQube_action_sper_sa_mearga"
on:
  push:
      branches:
      - main #sau poate main/backend/backend/src/main daca

  pull_request:
      types: [opened, synchronize, reopened]
  
  workflow_dispatch: #adica atunci cand pornesti manual scanarea

jobs:
  sonarqube:
    runs-on: ubuntu-latest #creaza un container
    steps:
    - name: Pregatire pt scanare
      uses: actions/checkout@v6 #cloneaza in container
      with: # Disabling shallow clones for improving the relevancy of reporting (nu stiu ce inseamna asta dar e recomandat)
        fetch-depth: 0

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
        
    - name: Scanare SonarQube
      run: mvn clean verify sonar:sonar -Dsonar.organization=fii-a5-ip -Dsonar.projectKey=fii-a5-ip_socially-backend
      working-directory: backend/backend
                  # JaCoCo este un set de teste pe care Sonar Qube le foloseste.

                # Astea aparent nu mai sunt de folos dar le las în caz că se schimbă ceva.  
                #args: >
                #-Dsonar.organization=fii-a5-ip
                #-Dsonar.projectKey=fii-a5-ip_socially-backend
                #-Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL}}

    # Incompatibil cu noile modificări:
    # - name: Timer uses: SonarSource/sonarqube-quality-gate-action@v1timeout-minutes: 5
      
